//指定版本 使用protobuf3

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.7.1
// source: te.proto

//每个 *.proto 文件可以指定 package 作为生成语言的 namespace

package example

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Person_Skills int32

const (
	Person_GOLANG Person_Skills = 0
	Person_PYTHON Person_Skills = 1
	Person_JAVA   Person_Skills = 2
	Person_RUST   Person_Skills = 3
	Person_CPP    Person_Skills = 4
)

// Enum value maps for Person_Skills.
var (
	Person_Skills_name = map[int32]string{
		0: "GOLANG",
		1: "PYTHON",
		2: "JAVA",
		3: "RUST",
		4: "CPP",
	}
	Person_Skills_value = map[string]int32{
		"GOLANG": 0,
		"PYTHON": 1,
		"JAVA":   2,
		"RUST":   3,
		"CPP":    4,
	}
)

func (x Person_Skills) Enum() *Person_Skills {
	p := new(Person_Skills)
	*p = x
	return p
}

func (x Person_Skills) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Person_Skills) Descriptor() protoreflect.EnumDescriptor {
	return file_te_proto_enumTypes[0].Descriptor()
}

func (Person_Skills) Type() protoreflect.EnumType {
	return &file_te_proto_enumTypes[0]
}

func (x Person_Skills) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Person_Skills.Descriptor instead.
func (Person_Skills) EnumDescriptor() ([]byte, []int) {
	return file_te_proto_rawDescGZIP(), []int{0, 0}
}

// message 用来定义一个数据结构
// repeated 的使用：被 repeated 标识的字段可以理解为是一个数组
// enum 类型使用：枚举用来表示一定范围内具有相同属性的值
// message 类型的使用： message 在定义过程中是可以声明自己定义的 message 类型
// map 类型的使用：message 定义时可以使用 map 类型
type Person struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Age      int64                  `protobuf:"varint,1,opt,name=age,proto3" json:"age,omitempty"`                                                                                          //年龄
	Realname string                 `protobuf:"bytes,2,opt,name=realname,proto3" json:"realname,omitempty"`                                                                                 //真实姓名
	Sex      string                 `protobuf:"bytes,3,opt,name=sex,proto3" json:"sex,omitempty"`                                                                                           //性别
	Vehicle  []string               `protobuf:"bytes,4,rep,name=vehicle,proto3" json:"vehicle,omitempty"`                                                                                   //上班交通工具 可以有多份工作 string 类型的
	Skill    Person_Skills          `protobuf:"varint,5,opt,name=skill,proto3,enum=example.Person_Skills" json:"skill,omitempty"`                                                           //技能 枚举用来表示一定范围内具有相同属性的值
	WorkDay  *WorkDays              `protobuf:"bytes,6,opt,name=workDay,proto3" json:"workDay,omitempty"`                                                                                   //工作日 message 在定义过程中是可以声明自己定义的 message 类型
	Dept     map[string]*Department `protobuf:"bytes,7,rep,name=dept,proto3" json:"dept,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` //挂靠部门 map 类型的使用：message 定义时可以使用 map 类型
}

func (x *Person) Reset() {
	*x = Person{}
	if protoimpl.UnsafeEnabled {
		mi := &file_te_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Person) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Person) ProtoMessage() {}

func (x *Person) ProtoReflect() protoreflect.Message {
	mi := &file_te_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Person.ProtoReflect.Descriptor instead.
func (*Person) Descriptor() ([]byte, []int) {
	return file_te_proto_rawDescGZIP(), []int{0}
}

func (x *Person) GetAge() int64 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *Person) GetRealname() string {
	if x != nil {
		return x.Realname
	}
	return ""
}

func (x *Person) GetSex() string {
	if x != nil {
		return x.Sex
	}
	return ""
}

func (x *Person) GetVehicle() []string {
	if x != nil {
		return x.Vehicle
	}
	return nil
}

func (x *Person) GetSkill() Person_Skills {
	if x != nil {
		return x.Skill
	}
	return Person_GOLANG
}

func (x *Person) GetWorkDay() *WorkDays {
	if x != nil {
		return x.WorkDay
	}
	return nil
}

func (x *Person) GetDept() map[string]*Department {
	if x != nil {
		return x.Dept
	}
	return nil
}

type WorkDays struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Day int32 `protobuf:"varint,1,opt,name=day,proto3" json:"day,omitempty"`
}

func (x *WorkDays) Reset() {
	*x = WorkDays{}
	if protoimpl.UnsafeEnabled {
		mi := &file_te_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkDays) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkDays) ProtoMessage() {}

func (x *WorkDays) ProtoReflect() protoreflect.Message {
	mi := &file_te_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkDays.ProtoReflect.Descriptor instead.
func (*WorkDays) Descriptor() ([]byte, []int) {
	return file_te_proto_rawDescGZIP(), []int{1}
}

func (x *WorkDays) GetDay() int32 {
	if x != nil {
		return x.Day
	}
	return 0
}

type Department struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Department) Reset() {
	*x = Department{}
	if protoimpl.UnsafeEnabled {
		mi := &file_te_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Department) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Department) ProtoMessage() {}

func (x *Department) ProtoReflect() protoreflect.Message {
	mi := &file_te_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Department.ProtoReflect.Descriptor instead.
func (*Department) Descriptor() ([]byte, []int) {
	return file_te_proto_rawDescGZIP(), []int{2}
}

func (x *Department) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_te_proto protoreflect.FileDescriptor

var file_te_proto_rawDesc = []byte{
	0x0a, 0x08, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x65, 0x78, 0x61, 0x6d,
	0x70, 0x6c, 0x65, 0x22, 0xf9, 0x02, 0x0a, 0x06, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x12, 0x10,
	0x0a, 0x03, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x61, 0x67, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x61, 0x6c, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x61, 0x6c, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x73, 0x65, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x65, 0x78, 0x12, 0x18,
	0x0a, 0x07, 0x76, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x07, 0x76, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x12, 0x2c, 0x0a, 0x05, 0x73, 0x6b, 0x69, 0x6c,
	0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c,
	0x65, 0x2e, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x2e, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x73, 0x52,
	0x05, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x12, 0x2b, 0x0a, 0x07, 0x77, 0x6f, 0x72, 0x6b, 0x44, 0x61,
	0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c,
	0x65, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x44, 0x61, 0x79, 0x73, 0x52, 0x07, 0x77, 0x6f, 0x72, 0x6b,
	0x44, 0x61, 0x79, 0x12, 0x2d, 0x0a, 0x04, 0x64, 0x65, 0x70, 0x74, 0x18, 0x07, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x19, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x50, 0x65, 0x72, 0x73,
	0x6f, 0x6e, 0x2e, 0x44, 0x65, 0x70, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x04, 0x64, 0x65,
	0x70, 0x74, 0x1a, 0x4c, 0x0a, 0x09, 0x44, 0x65, 0x70, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x29, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x13, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x44, 0x65, 0x70, 0x61, 0x72,
	0x74, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01,
	0x22, 0x3d, 0x0a, 0x06, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x73, 0x12, 0x0a, 0x0a, 0x06, 0x47, 0x4f,
	0x4c, 0x41, 0x4e, 0x47, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x50, 0x59, 0x54, 0x48, 0x4f, 0x4e,
	0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x4a, 0x41, 0x56, 0x41, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04,
	0x52, 0x55, 0x53, 0x54, 0x10, 0x03, 0x12, 0x07, 0x0a, 0x03, 0x43, 0x50, 0x50, 0x10, 0x04, 0x22,
	0x1c, 0x0a, 0x08, 0x57, 0x6f, 0x72, 0x6b, 0x44, 0x61, 0x79, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x64,
	0x61, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x64, 0x61, 0x79, 0x22, 0x20, 0x0a,
	0x0a, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_te_proto_rawDescOnce sync.Once
	file_te_proto_rawDescData = file_te_proto_rawDesc
)

func file_te_proto_rawDescGZIP() []byte {
	file_te_proto_rawDescOnce.Do(func() {
		file_te_proto_rawDescData = protoimpl.X.CompressGZIP(file_te_proto_rawDescData)
	})
	return file_te_proto_rawDescData
}

var file_te_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_te_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_te_proto_goTypes = []interface{}{
	(Person_Skills)(0), // 0: example.Person.Skills
	(*Person)(nil),     // 1: example.Person
	(*WorkDays)(nil),   // 2: example.WorkDays
	(*Department)(nil), // 3: example.Department
	nil,                // 4: example.Person.DeptEntry
}
var file_te_proto_depIdxs = []int32{
	0, // 0: example.Person.skill:type_name -> example.Person.Skills
	2, // 1: example.Person.workDay:type_name -> example.WorkDays
	4, // 2: example.Person.dept:type_name -> example.Person.DeptEntry
	3, // 3: example.Person.DeptEntry.value:type_name -> example.Department
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_te_proto_init() }
func file_te_proto_init() {
	if File_te_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_te_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Person); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_te_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkDays); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_te_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Department); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_te_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_te_proto_goTypes,
		DependencyIndexes: file_te_proto_depIdxs,
		EnumInfos:         file_te_proto_enumTypes,
		MessageInfos:      file_te_proto_msgTypes,
	}.Build()
	File_te_proto = out.File
	file_te_proto_rawDesc = nil
	file_te_proto_goTypes = nil
	file_te_proto_depIdxs = nil
}
